name: Mi primer flujo de trabajo

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v5
        
        - name: Lista y lectura de archivos
          run: |
            echo "Mi primer flujo en Github"
            ls -lrta
            cat README.md
        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am a DRAGON... XD" >> luis.txt

      #  - name: Lista de Archivos
       #   run: ls -lrt
        #- name: leer Archivos
         # run: cat README.md 
