name: Configuracion Matrix
on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    ##sirve para ejecutar un mismo job en múltiples combinaciones de variables 
    ## (como sistemas operativos, versiones de lenguajes, dependencias, etc.) en paralelo.
    strategy:
        fail-fast: false
        max-parallel: 2
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        image: [hello-world, alpine]
        exclude:
            - images: alpine
              os: windows-latest
        include: 
            - images: amd64/alpine
              os: ubuntu-20.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo Docker Detalles
        run: docker info

      - name: Run Image on ${{ matrix.os }}
        run: docker run ${{ matrix.image }}
